jobs:
  include:
    - stage: test
      language: go
      go: 1.11.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make vet ineffassign test
    - stage: test
      language: go
      go: 1.12.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make vet ineffassign test
    - stage: test
      language: go
      go: 1.13.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make vet ineffassign test
